stages:
    - build
    - package

build_main:
    stage: build
    only:
        - main
    tags:
        - dev
    cache:
        paths:
            - node_modules/
            - packages/web-main/.next/cache/
        policy: pull-push
    artifacts:
        paths:
            - packages/web-main/i18n/
    script:
        - pnpm i
        - pnpm build:main
build_i18n:
    stage: build
    only:
        - main
    tags:
        - dev
    cache:
        paths:
            - node_modules/
            - packages/web-i18n/.next/cache/
        policy: pull-push
    artifacts:
        paths:
            - packages/web-i18n/i18n/
    script:
        - pnpm i
        - pnpm build:i18n
build_admin:
    stage: build
    only:
        - main
    tags:
        - dev
    cache:
        paths:
            - node_modules/
            - packages/web-admin/.next/cache/
        policy: pull-push
    artifacts:
        paths:
            - packages/web-admin/i18n/
    script:
        - pnpm i
        - pnpm build:admin

package_main:
    stage: package
    only:
        - main
    tags:
        - dev
    artifacts:
        paths:
            - packages/web-main/i18n/
    script:
        - docker login -u $DOCKER_USER --password $DOCKER_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY/clover/web/main:$CI_PIPELINE_IID -f ./docker/main.Dockerfile .
        - docker tag $CI_REGISTRY/clover/web/main:$CI_PIPELINE_IID $CI_REGISTRY/clover/web/main:latest
        - docker push $CI_REGISTRY/clover/web/main:$CI_PIPELINE_IID
        - docker push $CI_REGISTRY/clover/web/main:latest
        - docker rmi $CI_REGISTRY/clover/web/main:$CI_PIPELINE_IID
        - docker rmi $CI_REGISTRY/clover/web/main:latest
package_i18n:
    stage: package
    only:
        - main
    tags:
        - dev
    artifacts:
        paths:
            - packages/web-i18n/i18n/
    script:
        - docker login -u $DOCKER_USER --password $DOCKER_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY/clover/web/i18n:$CI_PIPELINE_IID -f ./docker/i18n.Dockerfile .
        - docker tag $CI_REGISTRY/clover/web/i18n:$CI_PIPELINE_IID $CI_REGISTRY/clover/web/i18n:latest
        - docker push $CI_REGISTRY/clover/web/i18n:$CI_PIPELINE_IID
        - docker push $CI_REGISTRY/clover/web/i18n:latest
        - docker rmi $CI_REGISTRY/clover/web/i18n:$CI_PIPELINE_IID
        - docker rmi $CI_REGISTRY/clover/web/i18n:latest
package_admin:
    stage: package
    only:
        - main
    tags:
        - dev
    artifacts:
        paths:
            - packages/web-admin/i18n/
    script:
        - docker login -u $DOCKER_USER --password $DOCKER_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY/clover/web/admin:$CI_PIPELINE_IID -f ./docker/admin.Dockerfile .
        - docker tag $CI_REGISTRY/clover/web/admin:$CI_PIPELINE_IID $CI_REGISTRY/clover/web/admin:latest
        - docker push $CI_REGISTRY/clover/web/admin:$CI_PIPELINE_IID
        - docker push $CI_REGISTRY/clover/web/admin:latest
        - docker rmi $CI_REGISTRY/clover/web/admin:$CI_PIPELINE_IID
        - docker rmi $CI_REGISTRY/clover/web/admin:latest
