stages:
  - package
  - deploy

package-www:
  stage: package
  only:
    - /^www-.*$/
  tags:
    - dev
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY/clover/web/www:$CI_PIPELINE_ID -f ./docker/www.Dockerfile .
    - docker tag $CI_REGISTRY/clover/web/www:$CI_PIPELINE_ID $CI_REGISTRY/clover/web/www:latest
    - docker push $CI_REGISTRY/clover/web/www:$CI_PIPELINE_ID
    - docker push $CI_REGISTRY/clover/web/www:latest
    - docker rmi $CI_REGISTRY/clover/web/www:$CI_PIPELINE_ID
    - docker rmi $CI_REGISTRY/clover/web/www:latest

package-main:
  stage: package
  only:
    - /^main-.*$/
  tags:
    - dev
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY/clover/web/main:$CI_PIPELINE_ID -f ./docker/main.Dockerfile .
    - docker tag $CI_REGISTRY/clover/web/main:$CI_PIPELINE_ID $CI_REGISTRY/clover/web/main:latest
    - docker push $CI_REGISTRY/clover/web/main:$CI_PIPELINE_ID
    - docker push $CI_REGISTRY/clover/web/main:latest
    - docker rmi $CI_REGISTRY/clover/web/main:$CI_PIPELINE_ID
    - docker rmi $CI_REGISTRY/clover/web/main:latest

package-i18n:
  stage: package
  only:
    - /^i18n-.*$/
  tags:
    - dev
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY/clover/web/i18n:$CI_PIPELINE_ID -f ./docker/i18n.Dockerfile .
    - docker tag $CI_REGISTRY/clover/web/i18n:$CI_PIPELINE_ID $CI_REGISTRY/clover/web/i18n:latest
    - docker push $CI_REGISTRY/clover/web/i18n:$CI_PIPELINE_ID
    - docker push $CI_REGISTRY/clover/web/i18n:latest
    - docker rmi $CI_REGISTRY/clover/web/i18n:$CI_PIPELINE_ID
    - docker rmi $CI_REGISTRY/clover/web/i18n:latest

package-admin:
  stage: package
  only:
    - /^admin-.*$/
  tags:
    - dev
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY/clover/web/admin:$CI_PIPELINE_ID -f ./docker/admin.Dockerfile .
    - docker tag $CI_REGISTRY/clover/web/admin:$CI_PIPELINE_ID $CI_REGISTRY/clover/web/admin:latest
    - docker push $CI_REGISTRY/clover/web/admin:$CI_PIPELINE_ID
    - docker push $CI_REGISTRY/clover/web/admin:latest
    - docker rmi $CI_REGISTRY/clover/web/admin:$CI_PIPELINE_ID
    - docker rmi $CI_REGISTRY/clover/web/admin:latest

package-wiki:
  stage: package
  only:
    - /^wiki-.*$/
  tags:
    - dev
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY/clover/web/wiki:$CI_PIPELINE_ID -f ./docker/wiki.Dockerfile .
    - docker tag $CI_REGISTRY/clover/web/wiki:$CI_PIPELINE_ID $CI_REGISTRY/clover/web/wiki:latest
    - docker push $CI_REGISTRY/clover/web/wiki:$CI_PIPELINE_ID
    - docker push $CI_REGISTRY/clover/web/wiki:latest
    - docker rmi $CI_REGISTRY/clover/web/wiki:$CI_PIPELINE_ID
    - docker rmi $CI_REGISTRY/clover/web/wiki:latest

deploy-www:
  stage: deploy
  only:
    - /^www-.*$/
  tags:
    - dev
  script:
    - cd ~/server/clover/web-www
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker compose down
    - docker compose up -d

deploy-main:
  stage: deploy
  only:
    - /^main-.*$/
  tags:
    - dev
  script:
    - cd ~/server/clover/web-main
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker compose down
    - docker compose up -d

deploy-i18n:
  stage: deploy
  only:
    - /^i18n-.*$/
  tags:
    - dev
  script:
    - cd ~/server/clover/web-i18n
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker compose down
    - docker compose up -d

deploy-admin:
  stage: deploy
  only:
    - /^admin-.*$/
  tags:
    - dev
  script:
    - cd ~/server/clover/web-admin
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker compose down
    - docker compose up -d

deploy-wiki:
  stage: deploy
  only:
    - /^wiki-.*$/
  tags:
    - dev
  script:
    - cd ~/server/clover/web-wiki
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker compose down
    - docker compose up -d
