stages:
    - package
    - deploy

cache:
    paths:
        - node_modules/
        - packages/web-$SERVICE/.next/cache/
    policy: pull

package:
    stage: package
    only:
        variables:
            - $SERVICE == "main"
            - $SERVICE == "admin"
            - $SERVICE == "i18n"
    tags:
        - dev
    cache:
        paths:
            - node_modules/
            - packages/web-$SERVICE/.next/cache/
        policy: pull-push
    artifacts:
        paths:
            - packages/web-$SERVICE/i18n/
    script:
        - yarn
        - yarn build:$SERVICE
        - docker build -t clover-web-$SERVICE:$CI_PIPELINE_IID -f ./docker/$SERVICE.Dockerfile .
        - docker tag clover-web-$SERVICE:$CI_PIPELINE_IID clover-web-$SERVICE:latest

deploy:
    stage: deploy
    only:
        variables:
            - $SERVICE == "main"
            - $SERVICE == "admin"
            - $SERVICE == "i18n"
    tags:
        - dev
    script:
        - cd /opt/clover/test/web-$SERVICE
        - docker-compose down
        - docker-compose up -d
