export const JWT_SECRET = 'DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.';

export const IS_PUBLIC_KEY = 'isPublic';

export const ROLES_KEY = "roles";
